version: '3'

services:
  explorer:
    image: kuzudb/explorer:latest
    restart: unless-stopped
    environment:
      - MODE=READ_ONLY
    ports:
      - 8000:8000
    volumes:
      - ./transaction_db:/database

volumes:
  transaction_db: